First push
Alex-Nosov-ITMO/goTodoProject pull request #1
Opened 2024-05-21 18:53 UTC by Alex-Nosov-ITMO

Проект сделан на 80% 
Описание написал в README

2024-05-22 18:38 UTC, just-musha requested changes
Привет! Вижу что планируешь ещё добавить изменения. Давай я подожду и будем обсуждать финальную версию кода.

2024-05-22 18:38 UTC, just-musha commented on .env
> +#TODO_USER=postgres
Привет! Сразу напишу - первое что делаю при проверке запускаю тесты. Сейчас один падает, можешь проверить в чем дело?
```
--- FAIL: TestNextDate (0.02s)
    nextdate_3_test.go:51: 
        	Error Trace:	/home/mbulatova/projects/yandex-homeworks/sprint-final/goTodoProject-Alex-Nosov-ITMO/tests/nextdate_3_test.go:51
        	            				/home/mbulatova/projects/yandex-homeworks/sprint-final/goTodoProject-Alex-Nosov-ITMO/tests/nextdate_3_test.go:78
        	Error:      	Not equal: 
        	            	expected: "20240228"
        	            	actual  : "20240227"
        	            	
        	            	Diff:
        	            	--- Expected
        	            	+++ Actual
        	            	@@ -1 +1 @@
        	            	-20240228
        	            	+20240227
        	Test:       	TestNextDate
        	Messages:   	{"20240222", "m -2", "20240228"}
FAIL
FAIL	github.com/Alex-Nosov-ITMO/go_project_final/tests	0.218s
FAIL
```

2024-05-22 18:38 UTC, just-musha commented on cmd/main.go
> +	// оставил этот комментарий для будущей замены нахождения бд в корне проекта на миграции
Правильно ли понимаю, что это тоже входит в план на следующую итерацию? Не до конца поняла, что планируешь сделать. Присылай фиональную версию кода, и её будем уже обсуждать.

2024-05-29 16:03 UTC, Alex-Nosov-ITMO commented
Исправил ошибку, добавил решения со звездочками, логирование, аутенфикацию, swagger документацию.

2024-05-30 11:56 UTC, just-musha requested changes
Привет! Вижу что проделана большая работа. Отпрвляю комментарии по первой итерации ревью.

2024-05-30 11:56 UTC, just-musha commented on README.md
> +В добавок к ТЗ я сделал документацию swagger. (После запуска прилоения можно перейти по адресу /swagger/index.html и протестировать приложение там)
Топ :+1:

2024-05-30 11:56 UTC, just-musha commented on internal/nextDate/nextDate.go
> +	for _, num := range *arr {
А если `arr == nil` ? Нужна проверка

2024-05-30 11:56 UTC, just-musha commented on main.go
> +	"github.com/joho/godotenv"
Сортировка импортов - внешние пакеты обычно сразу после стандартных, отдельным блоком
И потом уже внутренние

2024-05-30 11:56 UTC, just-musha commented on pkg/handler/todo.go
> +		c.JSON(http.StatusInternalServerError, gin.H{"error": err.Error()})
Лучше логировать ошибку, а пользователю возвращать сообщение в духе "ошибка сервера". Вернуть сам текст ошибки может быть не безопасно

2024-05-30 11:56 UTC, just-musha commented on pkg/handler/todo.go
> +		c.JSON(http.StatusInternalServerError, gin.H{"error": err.Error()})
Валидно для всех моментов в коде, где, есть internal server error

2024-05-30 11:56 UTC, just-musha commented on pkg/repository/todo.go
> +	_ "github.com/lib/pq"
А это нужно?

2024-05-30 11:56 UTC, just-musha commented on pkg/repository/todo.go
> +	}
Здесь не забыть проверить ошибку rows.Err()

2024-05-30 11:56 UTC, just-musha commented on pkg/repository/todo.go
> +	}
И здесь

2024-05-30 11:56 UTC, just-musha commented on pkg/repository/todo.go
> +	return tasks, nil
И здесь

2024-05-30 11:56 UTC, just-musha commented on pkg/repository/todo.go
> +		return errors.New("ошибка при удалении задачи из базы данных")
Здесь лучше вернуть ошибку как есть, и использовать оборачивание. А залогировать где-то выше

2024-06-01 08:33 UTC, Alex-Nosov-ITMO commented
Поправил импорты и исправил логику логирования. Понял, что существует доп библиотека, где уже прописана функция errors.WithMessage, но исправлять уже не стал, так как сам ее прописал

2024-06-01 10:55 UTC, just-musha requested changes
Отлично! 

Написала комментарии - где можно подумать мб получится немного упростить (момент с оборачиванием ошибки)
Посмотри будешь ли сейчас править, это не прям крит, но вдруг тебе важно потом получить обратную связь. В целом - готова сейчас принять работу.

2024-06-01 10:55 UTC, just-musha commented on internal/myErrors/errors.go
> +	return errors.New(message + ": " + err.Error())
Для оборачивания лучше использовать встроенный способ - `fmt.Errorf("your message here: %w", err)`https://tproger.ru/articles/obrabotka-oshibok-v-go

Тк это позволит если что достать базовую `err` и использовать все методы ErrorIs, ErrorAs и т.д

2024-06-01 10:55 UTC, just-musha commented on internal/myErrors/errors.go
> +	"BadRequest": errors.New("неверный запрос").Error(),
Здесь выглядит немного избыточным завиодить `errors.New`, не будет ли достаточно просто строк?

Или даже ещё упростить и вместо мапы завести пачку переменных.

2024-06-01 11:32 UTC, Alex-Nosov-ITMO commented
Поправил замечания, вроде бы так должно быть

2024-06-01 15:49 UTC, just-musha approved these changes
Поздравляю! Работа принята! Получился качественный сервис, легкий в поддержке, хорошо документированный. Успехов в дальнейшем обучении и в работе.

2024-06-01 15:49 UTC, just-musha commented on internal/myErrors/errors.go
> +	return fmt.Errorf("%s: %w", message, err)
:+1:

2024-06-01 15:49 UTC, just-musha commented on internal/nextDate/nextDate.go
> +			return "", myErr.WithMassage("NextDate", errors.New("неверное количество аргументов правила повторения"))
` errors.New("неверное количество аргументов правила повторения"))`
вот эту ошибку можно в переменную вынести вверх файла, повторяется

2024-06-01 15:49 UTC, just-musha commented on internal/myErrors/errors.go
> +func WithMassage(message string, err error) error {
```diff
-WithMassage
+WithMessage
```

2024-06-30 02:25 UTC, merged